<!DOCTYPE html>
<html>
<head>
<!DOCTYPE html>
<html lang="en-us">



<link rel="stylesheet" href="/css/fonts.css">
<link rel="stylesheet" href="/css/main-site.css">
<link rel="stylesheet" href="/css/fa5-all.css">
<style type="text/css">
    body {
	background-color: #ffffff;
	color: #404040
}

/* Links */

a {
  color: #CA225E;
}

a:hover {
  color: #cc3168;
}

/* Landing page content bands */

#homeContent .band.first {
  background-color: #ffffff
}

#homeContent .band.second {
  background-color: #fcfcfc
}

#homeContent .band.third {
  background-color: #ffffff
}

/* Top navigation bar menu */

#rStudioHeader {
  background-color: #ffffff;
  color: black;
}

#rStudioHeader .productName {
  color: #CA225E
}

#rStudioHeader .productName:hover {
  color: #00000075
}

#rStudioHeader #menu .menuItem.a {
  background-color: #75aadb;
  color: black;
}

#rStudioHeader #menu .menuItem:hover {
  background-color: white;
  color: #CA225E;
}

#rStudioHeader #menu .menuItem.current {
  background-color: #fcfcfc;
  color: #CA225E;
  text-decoration: none;
}

/* Footer */

#rStudioFooter.band {
  background-color: #CA225E40;
}

#rStudioFooter .bandContent #copyright {
  color: #CA225E;
}

/* Tables */

table tbody tr:nth-child(even){
  background-color: #fcfcfc;
}

table tbody tr:nth-child(odd){
  background-color: #1a162d10;
}

.latest {
  border-top: .5em solid <no value>;
}
</style>

  <link rel="stylesheet" href="/css/tm.css">




<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<meta name="apple-mobile-web-app-capable" content="yes" />

<meta name="og:image" content="https://www.tidymodels.org/images/feature_summary_large_image.jpg" >

  <meta property="twitter:card" content="summary_large_image">

<meta name="twitter:image" content="https://www.tidymodels.org/images/feature_summary_large_image.jpg" ><meta name="generator" content="Hugo 0.96.0" />

<meta property="og:type" content="website"><title>Learn - Iterative Bayesian optimization of a classification model</title>
    <meta property="og:title" content="Learn - Iterative Bayesian optimization of a classification model">
    
    
    
    
    <meta property="description" content="Identify the best hyperparameters for a model using Bayesian optimization of iterative search.
">
    <meta property="og:description" content="Identify the best hyperparameters for a model using Bayesian optimization of iterative search.
">



<link rel="apple-touch-icon" sizes="180x180" href="/images/favicons/apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="32x32" href="/images/favicons/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="/images/favicons/favicon-16x16.png" />
<link rel="manifest" href="/images/favicons/site.webmanifest" />
<link rel="mask-icon" href="/images/favicons/safari-pinned-tab.svg" />
<link rel="shortcut icon" href="/images/favicons/favicon.ico" />
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" href="/images/favicons/browserconfig.xml" >



<script type="text/javascript" src="/js/jquery-3.5.1.min.js"></script>
<script type="text/javascript" src="/js/site.js"></script>


  <script type="text/javascript" src="/js/tm.js"></script>


<link rel="icon" href="/images/favicon.ico" />


<script defer data-domain="tidymodels.org,all.tidymodels.org" src="https://plausible.io/js/plausible.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>



  <body>
    <div id="appTidyverseSite" class="shrinkHeader alwaysShrinkHeader">
      <div id="main">
        
        <div id="rStudioHeader">
          <div class="band">
            <div class="innards bandContent">
              <div>
                <a class="productName" href="/">Tidymodels</a>
                
              </div>
              <div id="menu">
  <div id="menuToggler"></div>
  <div id="menuItems" class="">
    
    
      
      
      
    <a class="menuItem " href="/packages/">Packages</a>
    
      
      
      
    <a class="menuItem " href="/start/">Get Started</a>
    
      
      
      
    <a class="menuItem current" href="/learn/">Learn</a>
    
      
      
      
    <a class="menuItem " href="/help/">Help</a>
    
      
      
      
    <a class="menuItem " href="/contribute/">Contribute</a>
    
      
      
      
    <a class="menuItem " href="/find/"><i class="fas fa-search fa-lg"></i> </a>
    
      
      
      
    <a class="menuItem " href="https://github.com/tidymodels/"><i class="fab fa-github fa-lg"></i></a>
    
  </div>
</div>

            </div>
          </div>
        </div>
</head>
<body>


 




<div class="band padForHeader pushFooter">
  <div class="bandContent">
    <div class="full splitColumns withMobileMargins">
      <div class="column75">
        
        <div class="section">
          <div class="sectionTitle">
            <a href="/learn/">
              <i class="fas fa-chevron-left"></i>&nbsp;Back to Learn
            </a>
          </div>
        </div>

      <h1 class="article-title">Iterative Bayesian optimization of a classification model</h1>

      
      <div class="article-header">
        </div>
        

      
      
      
      
        </p>
      
        
      <div class="learning-objective-container">
        <h2 class="learning-objective">Learning objective</h2>
        <p class="single-learning-objective-text">Identify the best hyperparameters for a model using Bayesian optimization of iterative search.</p>
      </div>
      

      <div class="article-content">
      <h2 id="introduction">Introduction</h2>
<p>To use the code in this article, you will need to install the following packages: kernlab, modeldata, themis, and tidymodels.</p>
<p>Many of the examples for model tuning focus on <a href="/learn/work/tune-svm/">grid search</a>. For that method, all the candidate tuning parameter combinations are defined prior to evaluation. Alternatively, <em>iterative search</em> can be used to analyze the existing tuning parameter results and then <em>predict</em> which tuning parameters to try next.</p>
<p>There are a variety of methods for iterative search and the focus in this article is on <em>Bayesian optimization</em>. For more information on this method, these resources might be helpful:</p>
<ul>
<li>
<p><a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=Practical+Bayesian+Optimization+of+Machine+Learning+Algorithms&amp;btnG="><em>Practical bayesian optimization of machine learning algorithms</em></a> (2012). J Snoek, H Larochelle, and RP Adams. Advances in neural information.</p>
</li>
<li>
<p><a href="https://www.cs.toronto.edu/~rgrosse/courses/csc411_f18/tutorials/tut8_adams_slides.pdf"><em>A Tutorial on Bayesian Optimization for Machine Learning</em></a> (2018). R Adams.</p>
</li>
<li>
<p><a href="http://www.gaussianprocess.org/gpml/"><em>Gaussian Processes for Machine Learning</em></a> (2006). C E Rasmussen and C Williams.</p>
</li>
<li>
<p><a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=%22Bayesian+Optimization%22&amp;btnG=">Other articles!</a></p>
</li>
</ul>
<h2 id="cell-segmenting-revisited">Cell segmenting revisited</h2>
<p>To demonstrate this approach to tuning models, let&rsquo;s return to the cell segmentation data from the <a href="/start/resampling/">Getting Started</a> article on resampling:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">library</span>(tidymodels)
</span></span><span style="display:flex;"><span><span style="color:#00f">library</span>(modeldata)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic"># Load data</span>
</span></span><span style="display:flex;"><span><span style="color:#00f">data</span>(cells)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#00f">set.seed</span>(<span style="color:#666">2369</span>)
</span></span><span style="display:flex;"><span>tr_te_split <span style="color:#666">&lt;-</span> <span style="color:#00f">initial_split</span>(cells <span style="color:#666">%&gt;%</span> <span style="color:#00f">select</span>(<span style="color:#666">-</span>case), prop <span style="color:#666">=</span> <span style="color:#666">3</span><span style="color:#666">/</span><span style="color:#666">4</span>)
</span></span><span style="display:flex;"><span>cell_train <span style="color:#666">&lt;-</span> <span style="color:#00f">training</span>(tr_te_split)
</span></span><span style="display:flex;"><span>cell_test  <span style="color:#666">&lt;-</span> <span style="color:#00f">testing</span>(tr_te_split)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#00f">set.seed</span>(<span style="color:#666">1697</span>)
</span></span><span style="display:flex;"><span>folds <span style="color:#666">&lt;-</span> <span style="color:#00f">vfold_cv</span>(cell_train, v <span style="color:#666">=</span> <span style="color:#666">10</span>)
</span></span></code></pre></div><h2 id="the-tuning-scheme">The tuning scheme</h2>
<p>Since the predictors are highly correlated, we can used a recipe to convert the original predictors to principal component scores. There is also slight class imbalance in these data; about 64% of the data are poorly segmented. To mitigate this, the data will be down-sampled at the end of the pre-processing so that the number of poorly and well segmented cells occur with equal frequency. We can use a recipe for all this pre-processing, but the number of principal components will need to be <em>tuned</em> so that we have enough (but not too many) representations of the data.</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">library</span>(themis)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>cell_pre_proc <span style="color:#666">&lt;-</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">recipe</span>(class <span style="color:#666">~</span> ., data <span style="color:#666">=</span> cell_train) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">step_YeoJohnson</span>(<span style="color:#00f">all_predictors</span>()) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">step_normalize</span>(<span style="color:#00f">all_predictors</span>()) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">step_pca</span>(<span style="color:#00f">all_predictors</span>(), num_comp <span style="color:#666">=</span> <span style="color:#00f">tune</span>()) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">step_downsample</span>(class)
</span></span></code></pre></div><p>In this analysis, we will use a support vector machine to model the data. Let&rsquo;s use a radial basis function (RBF) kernel and tune its main parameter ($\sigma$). Additionally, the main SVM parameter, the cost value, also needs optimization.</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>svm_mod <span style="color:#666">&lt;-</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">svm_rbf</span>(mode <span style="color:#666">=</span> <span style="color:#ba2121">&#34;classification&#34;</span>, cost <span style="color:#666">=</span> <span style="color:#00f">tune</span>(), rbf_sigma <span style="color:#666">=</span> <span style="color:#00f">tune</span>()) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">set_engine</span>(<span style="color:#ba2121">&#34;kernlab&#34;</span>)
</span></span></code></pre></div><p>These two objects (the recipe and model) will be combined into a single object via the <code>workflow()</code> function from the <a href="https://workflows.tidymodels.org/">workflows</a> package; this object will be used in the optimization process.</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>svm_wflow <span style="color:#666">&lt;-</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">workflow</span>() <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">add_model</span>(svm_mod) <span style="color:#666">%&gt;%</span>
</span></span><span style="display:flex;"><span>  <span style="color:#00f">add_recipe</span>(cell_pre_proc)
</span></span></code></pre></div><p>From this object, we can derive information about what parameters are slated to be tuned. A parameter set is derived by:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>svm_set <span style="color:#666">&lt;-</span> <span style="color:#00f">extract_parameter_set_dials</span>(svm_wflow)
</span></span><span style="display:flex;"><span>svm_set
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; Collection of 3 parameters for tuning</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  identifier      type    object</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;        cost      cost nparam[+]</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;   rbf_sigma rbf_sigma nparam[+]</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;    num_comp  num_comp nparam[+]</span>
</span></span></code></pre></div><p>The default range for the number of PCA components is rather small for this data set. A member of the parameter set can be modified using the <code>update()</code> function. Let&rsquo;s constrain the search to one to twenty components by updating the <code>num_comp</code> parameter. Additionally, the lower bound of this parameter is set to zero which specifies that the original predictor set should also be evaluated (i.e., with no PCA step at all):</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>svm_set <span style="color:#666">&lt;-</span> 
</span></span><span style="display:flex;"><span>  svm_set <span style="color:#666">%&gt;%</span> 
</span></span><span style="display:flex;"><span>  <span style="color:#00f">update</span>(num_comp <span style="color:#666">=</span> <span style="color:#00f">num_comp</span>(<span style="color:#00f">c</span>(<span style="color:#666">0L</span>, <span style="color:#666">20L</span>)))
</span></span></code></pre></div><h2 id="sequential-tuning">Sequential tuning</h2>
<p>Bayesian optimization is a sequential method that uses a model to predict new candidate parameters for assessment. When scoring potential parameter value, the mean and variance of performance are predicted. The strategy used to define how these two statistical quantities are used is defined by an <em>acquisition function</em>.</p>
<p>For example, one approach for scoring new candidates is to use a confidence bound. Suppose accuracy is being optimized. For a metric that we want to maximize, a lower confidence bound can be used. The multiplier on the standard error (denoted as <code>\(\kappa\)</code>) is a value that can be used to make trade-offs between <strong>exploration</strong> and <strong>exploitation</strong>.</p>
<ul>
<li>
<p><strong>Exploration</strong> means that the search will consider candidates in untested space.</p>
</li>
<li>
<p><strong>Exploitation</strong> focuses in areas where the previous best results occurred.</p>
</li>
</ul>
<p>The variance predicted by the Bayesian model is mostly spatial variation; the value will be large for candidate values that are not close to values that have already been evaluated. If the standard error multiplier is high, the search process will be more likely to avoid areas without candidate values in the vicinity.</p>
<p>We&rsquo;ll use another acquisition function, <em>expected improvement</em>, that determines which candidates are likely to be helpful relative to the current best results. This is the default acquisition function. More information on these functions can be found in the <a href="https://tune.tidymodels.org/articles/acquisition_functions.html">package vignette for acquisition functions</a>.</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">set.seed</span>(<span style="color:#666">12</span>)
</span></span><span style="display:flex;"><span>search_res <span style="color:#666">&lt;-</span>
</span></span><span style="display:flex;"><span>  svm_wflow <span style="color:#666">%&gt;%</span> 
</span></span><span style="display:flex;"><span>  <span style="color:#00f">tune_bayes</span>(
</span></span><span style="display:flex;"><span>    resamples <span style="color:#666">=</span> folds,
</span></span><span style="display:flex;"><span>    <span style="color:#408080;font-style:italic"># To use non-default parameter ranges</span>
</span></span><span style="display:flex;"><span>    param_info <span style="color:#666">=</span> svm_set,
</span></span><span style="display:flex;"><span>    <span style="color:#408080;font-style:italic"># Generate five at semi-random to start</span>
</span></span><span style="display:flex;"><span>    initial <span style="color:#666">=</span> <span style="color:#666">5</span>,
</span></span><span style="display:flex;"><span>    iter <span style="color:#666">=</span> <span style="color:#666">50</span>,
</span></span><span style="display:flex;"><span>    <span style="color:#408080;font-style:italic"># How to measure performance?</span>
</span></span><span style="display:flex;"><span>    metrics <span style="color:#666">=</span> <span style="color:#00f">metric_set</span>(roc_auc),
</span></span><span style="display:flex;"><span>    control <span style="color:#666">=</span> <span style="color:#00f">control_bayes</span>(no_improve <span style="color:#666">=</span> <span style="color:#666">30</span>, verbose <span style="color:#666">=</span> <span style="color:#008000;font-weight:bold">TRUE</span>)
</span></span><span style="display:flex;"><span>  )
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; &gt;  Generating a set of 5 initial parameter results</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Initialization complete</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; Optimizing roc_auc using the expected improvement</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 1 ───────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8764 (@iter 0)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00386, rbf_sigma=0.00513, num_comp=19</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.8797 (+/-0.0108)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 2 ───────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8797 (@iter 1)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.245, rbf_sigma=0.00334, num_comp=2</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7966 (+/-0.0103)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 3 ───────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8797 (@iter 1)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=25.8, rbf_sigma=0.00543, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.8881 (+/-0.00921)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 4 ───────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8881 (@iter 3)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.403, rbf_sigma=0.944, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.387 (+/-0.0833)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 5 ───────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8881 (@iter 3)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0315, rbf_sigma=0.00228, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8806 (+/-0.0114)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 6 ───────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8881 (@iter 3)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=24.8, rbf_sigma=0.0041, num_comp=17</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.8882 (+/-0.00987)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 7 ───────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8882 (@iter 6)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=27.5, rbf_sigma=0.00924, num_comp=16</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.8883 (+/-0.0105)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 8 ───────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8883 (@iter 7)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=5.6, rbf_sigma=0.00774, num_comp=14</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.8894 (+/-0.0109)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 9 ───────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8894 (@iter 8)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=6.12, rbf_sigma=0.0063, num_comp=17</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.885 (+/-0.0103)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 10 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8894 (@iter 8)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=16.6, rbf_sigma=0.00343, num_comp=19</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8869 (+/-0.00985)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 11 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8894 (@iter 8)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=19.5, rbf_sigma=0.0082, num_comp=15</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.8943 (+/-0.0101)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 12 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8943 (@iter 11)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=15.1, rbf_sigma=1.09e-10, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.3451 (+/-0.116)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 13 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8943 (@iter 11)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=7.19, rbf_sigma=0.00528, num_comp=15</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8868 (+/-0.0107)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 14 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8943 (@iter 11)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=11.8, rbf_sigma=0.00143, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8811 (+/-0.0112)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 15 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8943 (@iter 11)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=23.9, rbf_sigma=0.015, num_comp=15</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8853 (+/-0.0123)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 16 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8943 (@iter 11)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=29.4, rbf_sigma=0.00841, num_comp=18</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8823 (+/-0.0105)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 17 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8943 (@iter 11)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00117, rbf_sigma=0.0112, num_comp=14</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8771 (+/-0.0119)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 18 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.8943 (@iter 11)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=16.7, rbf_sigma=0.0137, num_comp=10</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.9 (+/-0.00986)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 19 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9 (@iter 18)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=31.9, rbf_sigma=0.0147, num_comp=8</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8985 (+/-0.0101)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 20 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9 (@iter 18)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=8.72, rbf_sigma=0.0184, num_comp=9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.9021 (+/-0.0101)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 21 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 20)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=17.4, rbf_sigma=0.0158, num_comp=10</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.9005 (+/-0.0099)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 22 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 20)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=20.4, rbf_sigma=0.0214, num_comp=9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.9001 (+/-0.0102)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 23 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 20)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=13.8, rbf_sigma=0.0145, num_comp=9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.9018 (+/-0.0101)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 24 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 20)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=14.8, rbf_sigma=0.017, num_comp=9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ♥ Newest results:	roc_auc=0.9021 (+/-0.00998)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 25 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=17.2, rbf_sigma=0.0083, num_comp=10</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8986 (+/-0.00973)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 26 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=20, rbf_sigma=0.018, num_comp=9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.9011 (+/-0.0102)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 27 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0185, rbf_sigma=0.0151, num_comp=9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8774 (+/-0.0123)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 28 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00426, rbf_sigma=0.0181, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8841 (+/-0.0108)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 29 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00102, rbf_sigma=0.00959, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8832 (+/-0.011)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 30 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.983, rbf_sigma=0.0204, num_comp=10</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8917 (+/-0.0106)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 31 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=14.2, rbf_sigma=0.0104, num_comp=8</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8977 (+/-0.01)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 32 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=14.5, rbf_sigma=0.0114, num_comp=11</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8971 (+/-0.00976)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 33 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=19.4, rbf_sigma=0.0126, num_comp=9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.9017 (+/-0.00997)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 34 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=11.8, rbf_sigma=0.0207, num_comp=9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.902 (+/-0.00981)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 35 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=12.6, rbf_sigma=0.0164, num_comp=8</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8987 (+/-0.0102)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 36 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=22.7, rbf_sigma=0.000423, num_comp=1</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7725 (+/-0.0106)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 37 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=9.21, rbf_sigma=0.0192, num_comp=9</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.9017 (+/-0.00992)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 38 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00227, rbf_sigma=0.0278, num_comp=15</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8828 (+/-0.0113)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 39 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0012, rbf_sigma=0.000867, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.3449 (+/-0.116)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 40 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.118, rbf_sigma=0.00525, num_comp=19</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8806 (+/-0.0112)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 41 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=25.1, rbf_sigma=0.00223, num_comp=17</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8811 (+/-0.0108)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 42 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.892, rbf_sigma=0.00268, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8818 (+/-0.0116)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 43 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0108, rbf_sigma=0.00733, num_comp=18</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8756 (+/-0.0121)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 44 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.061, rbf_sigma=0.00356, num_comp=20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.881 (+/-0.0113)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 45 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00135, rbf_sigma=0.0218, num_comp=2</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7966 (+/-0.0104)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 46 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.0476, rbf_sigma=0.0248, num_comp=17</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8809 (+/-0.0113)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 47 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00158, rbf_sigma=0.0689, num_comp=19</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8784 (+/-0.0101)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 48 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=0.00171, rbf_sigma=0.0337, num_comp=19</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.8836 (+/-0.0104)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 49 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=29.2, rbf_sigma=0.000104, num_comp=15</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.875 (+/-0.0122)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ── Iteration 50 ──────────────────────────────────────────────────────</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Current best:		roc_auc=0.9021 (@iter 24)</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Gaussian process model</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Generating 5000 candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Predicted candidates</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i cost=30.2, rbf_sigma=4.34e-05, num_comp=2</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; i Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ✓ Estimating performance</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; ⓧ Newest results:	roc_auc=0.7965 (+/-0.0104)</span>
</span></span></code></pre></div><p>The resulting tibble is a stacked set of rows of the rsample object with an additional column for the iteration number:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>search_res
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # Tuning results</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # 10-fold cross-validation </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # A tibble: 510 × 5</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;    splits             id     .metrics         .notes           .iter</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;    &lt;list&gt;             &lt;chr&gt;  &lt;list&gt;           &lt;list&gt;           &lt;int&gt;</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  1 &lt;split [1362/152]&gt; Fold01 &lt;tibble [5 × 7]&gt; &lt;tibble [0 × 3]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  2 &lt;split [1362/152]&gt; Fold02 &lt;tibble [5 × 7]&gt; &lt;tibble [0 × 3]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  3 &lt;split [1362/152]&gt; Fold03 &lt;tibble [5 × 7]&gt; &lt;tibble [0 × 3]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  4 &lt;split [1362/152]&gt; Fold04 &lt;tibble [5 × 7]&gt; &lt;tibble [0 × 3]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  5 &lt;split [1363/151]&gt; Fold05 &lt;tibble [5 × 7]&gt; &lt;tibble [0 × 3]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  6 &lt;split [1363/151]&gt; Fold06 &lt;tibble [5 × 7]&gt; &lt;tibble [0 × 3]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  7 &lt;split [1363/151]&gt; Fold07 &lt;tibble [5 × 7]&gt; &lt;tibble [0 × 3]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  8 &lt;split [1363/151]&gt; Fold08 &lt;tibble [5 × 7]&gt; &lt;tibble [0 × 3]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  9 &lt;split [1363/151]&gt; Fold09 &lt;tibble [5 × 7]&gt; &lt;tibble [0 × 3]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 10 &lt;split [1363/151]&gt; Fold10 &lt;tibble [5 × 7]&gt; &lt;tibble [0 × 3]&gt;     0</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # … with 500 more rows</span>
</span></span></code></pre></div><p>As with grid search, we can summarize the results over resamples:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span>estimates <span style="color:#666">&lt;-</span> 
</span></span><span style="display:flex;"><span>  <span style="color:#00f">collect_metrics</span>(search_res) <span style="color:#666">%&gt;%</span> 
</span></span><span style="display:flex;"><span>  <span style="color:#00f">arrange</span>(.iter)
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>estimates
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # A tibble: 55 × 10</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;        cost    rbf_sigma num_comp .metric .estimator  mean     n std_err .config</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;       &lt;dbl&gt;        &lt;dbl&gt;    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;  </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  1  0.00207      1.56e-5       10 roc_auc binary     0.345    10 0.114   Prepro…</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  2  0.348        4.43e-2        1 roc_auc binary     0.773    10 0.0106  Prepro…</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  3 15.5          1.28e-7       20 roc_auc binary     0.345    10 0.116   Prepro…</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  4  1.45         2.04e-3       15 roc_auc binary     0.876    10 0.0121  Prepro…</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  5  0.0304       6.41e-9        5 roc_auc binary     0.345    10 0.113   Prepro…</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  6  0.00386      5.13e-3       19 roc_auc binary     0.880    10 0.0108  Iter1  </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  7  0.245        3.34e-3        2 roc_auc binary     0.797    10 0.0103  Iter2  </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  8 25.8          5.43e-3       20 roc_auc binary     0.888    10 0.00921 Iter3  </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;  9  0.403        9.44e-1       20 roc_auc binary     0.387    10 0.0833  Iter4  </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 10  0.0315       2.28e-3       20 roc_auc binary     0.881    10 0.0114  Iter5  </span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # … with 45 more rows, and 1 more variable: .iter &lt;int&gt;</span>
</span></span></code></pre></div><p>The best performance of the initial set of candidate values was <code>AUC = 0.876 </code>. The best results were achieved at iteration 24 with a corresponding AUC value of 0.902. The five best results are:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">show_best</span>(search_res, metric <span style="color:#666">=</span> <span style="color:#ba2121">&#34;roc_auc&#34;</span>)
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; # A tibble: 5 × 10</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;    cost rbf_sigma num_comp .metric .estimator  mean     n std_err .config .iter</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;int&gt;</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 1 14.8     0.0170        9 roc_auc binary     0.902    10 0.00998 Iter24     24</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 2  8.72    0.0184        9 roc_auc binary     0.902    10 0.0101  Iter20     20</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 3 11.8     0.0207        9 roc_auc binary     0.902    10 0.00981 Iter34     34</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 4 13.8     0.0145        9 roc_auc binary     0.902    10 0.0101  Iter23     23</span>
</span></span><span style="display:flex;"><span><span style="color:#408080;font-style:italic">#&gt; 5 19.4     0.0126        9 roc_auc binary     0.902    10 0.00997 Iter33     33</span>
</span></span></code></pre></div><p>A plot of the search iterations can be created via:</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">autoplot</span>(search_res, type <span style="color:#666">=</span> <span style="color:#ba2121">&#34;performance&#34;</span>)
</span></span></code></pre></div><img src="figs/bo-plot-1.svg" width="672" />
<p>There are many parameter combinations have roughly equivalent results.</p>
<p>How did the parameters change over iterations?</p>
<div class="highlight"><pre tabindex="0" style=";-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-r" data-lang="r"><span style="display:flex;"><span><span style="color:#00f">autoplot</span>(search_res, type <span style="color:#666">=</span> <span style="color:#ba2121">&#34;parameters&#34;</span>) <span style="color:#666">+</span> 
</span></span><span style="display:flex;"><span>  <span style="color:#00f">labs</span>(x <span style="color:#666">=</span> <span style="color:#ba2121">&#34;Iterations&#34;</span>, y <span style="color:#666">=</span> <span style="color:#008000;font-weight:bold">NULL</span>)
</span></span></code></pre></div><img src="figs/bo-param-plot-1.svg" width="864" />
<h2 id="session-information">Session information</h2>
<pre tabindex="0"><code>#&gt; ─ Session info ─────────────────────────────────────────────────────
#&gt;  setting  value
#&gt;  version  R version 4.1.2 (2021-11-01)
#&gt;  os       macOS Monterey 12.3
#&gt;  system   aarch64, darwin20
#&gt;  ui       X11
#&gt;  language (EN)
#&gt;  collate  en_GB.UTF-8
#&gt;  ctype    en_GB.UTF-8
#&gt;  tz       Europe/London
#&gt;  date     2022-04-11
#&gt;  pandoc   2.14.0.3 @ /Applications/RStudio.app/Contents/MacOS/pandoc/ (via rmarkdown)
#&gt; 
#&gt; ─ Packages ─────────────────────────────────────────────────────────
#&gt;  package    * version date (UTC) lib source
#&gt;  broom      * 0.7.12  2022-01-28 [1] CRAN (R 4.1.1)
#&gt;  dials      * 0.1.1   2022-04-06 [1] CRAN (R 4.1.2)
#&gt;  dplyr      * 1.0.8   2022-02-08 [1] CRAN (R 4.1.2)
#&gt;  ggplot2    * 3.3.5   2021-06-25 [1] CRAN (R 4.1.1)
#&gt;  infer      * 1.0.0   2021-08-13 [1] CRAN (R 4.1.1)
#&gt;  kernlab    * 0.9-30  2022-04-02 [1] CRAN (R 4.1.2)
#&gt;  modeldata  * 0.1.1   2021-07-14 [1] CRAN (R 4.1.2)
#&gt;  parsnip    * 0.2.1   2022-03-17 [1] CRAN (R 4.1.1)
#&gt;  purrr      * 0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
#&gt;  recipes    * 0.2.0   2022-02-18 [1] CRAN (R 4.1.1)
#&gt;  rlang      * 1.0.2   2022-03-04 [1] CRAN (R 4.1.1)
#&gt;  rsample    * 0.1.1   2021-11-08 [1] CRAN (R 4.1.2)
#&gt;  themis     * 0.2.0   2022-03-30 [1] CRAN (R 4.1.1)
#&gt;  tibble     * 3.1.6   2021-11-07 [1] CRAN (R 4.1.1)
#&gt;  tidymodels * 0.2.0   2022-03-19 [1] CRAN (R 4.1.1)
#&gt;  tune       * 0.2.0   2022-03-19 [1] CRAN (R 4.1.2)
#&gt;  workflows  * 0.2.6   2022-03-18 [1] CRAN (R 4.1.2)
#&gt;  yardstick  * 0.0.9   2021-11-22 [1] CRAN (R 4.1.1)
#&gt; 
#&gt;  [1] /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
#&gt; 
#&gt; ────────────────────────────────────────────────────────────────────
</code></pre>
      </div>


      <div class="article-footer">
      
      <div style="float:left">
      
        <div class='itemTitle' align="left" style='font-size:.8em; line-height:2em'>Previous</div>
        <a href="/learn/work/nested-resampling/">Nested resampling</a>
      
      </div>
      
      
      <div style="float:right">
      
      <div class='itemTitle' align="right" style='font-size:.8em; line-height:2em'>Next</div>
        <a href="/learn/work/tune-text/">Tuning text models</a>
      
      </div>
     </div> 

      </div>

      <div class="column25">
        <div class="section hideOnMobile">
          <div class="sectionTitle">Contents</div>
          <nav id="TableOfContents">
  <ul>
    <li><a href="#introduction">Introduction</a></li>
    <li><a href="#cell-segmenting-revisited">Cell segmenting revisited</a></li>
    <li><a href="#the-tuning-scheme">The tuning scheme</a></li>
    <li><a href="#sequential-tuning">Sequential tuning</a></li>
    <li><a href="#session-information">Session information</a></li>
  </ul>
</nav>
        </div>
      
        <div class="section">
          <div class="sectionTitle">Resources</div>
          




<div class="event">
  
  <div class="eventTitle">
    <a href="/find/"><i class="fas fa-search fa-xs"></i>&nbsp;&nbsp;Find</a>
  </div>
  <div class="eventDetails">Explore searchable tables of all tidymodels packages and functions.</div>
</div>






<div class="event">
  
  <div class="eventTitle">
    <a href="/books/"><i class="fas fa-book-open fa-xs"></i>&nbsp;&nbsp;Books</a>
  </div>
  <div class="eventDetails">Study up on statistics and modeling with our comprehensive books.</div>
</div>






<div class="event">
  
  <div class="eventTitle">
    <a href="https://www.tidyverse.org/tags/tidymodels/" target="_blank"><i class="fas fa-bullhorn fa-xs"></i>&nbsp;&nbsp;News</a>
  </div>
  <div class="eventDetails">Hear the latest about tidymodels packages at the <a href="https://www.tidyverse.org/tags/tidymodels/">tidyverse blog</a>.</div>
</div>



        </div>
      </div>
      


    </div>
  </div>  
</div> 


        <div id="rStudioFooter" class="band">
          <div class="bandContent">
            <div id="copyright">
              
              
              Proudly supported by <a class="rstudioLogo" href="https://www.rstudio.com/"></a>
              
            </div>
            <div id="logos">
              
              
            </div>
            
            <span class="float-right" aria-hidden="true">
              <a href="#" class="back-to-top">
                <span class="button_icon">
                  <i class="fas fa-chevron-up fa-2x"></i>
                </span>
              </a>
            </span>
            
          </div>
        </div>

      </div>  
    </div>  

    

    
<script src="/js/math-code.js"></script>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$','$'], ['\\(','\\)']],
    processEscapes: true
  }
});
</script>
<script async src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-20375833-29', 'auto');
	
	ga('send', 'pageview');
}
</script>

  </body>
</html>

</body>
</html>
